rejmerge.in: refactor, use PAGER instead of hardcoded more(1)

diff --git a/rejmerge.in b/rejmerge.in
--- a/rejmerge.in
+++ b/rejmerge.in
@@ -79,8 +79,8 @@ permissions_menu() {
 					chown --reference="$1" "$2"
 					chmod --reference="$1" "$2"
 				else
-					chown $(stat -t "$1" | awk '{print $5":"$6}') $2
-					chmod $(stat -t "$1" | awk '{print $4}') $2
+					chown $(stat -t "$1" | awk '{print $5":"$6}') "$2"
+					chmod $(stat -t "$1" | awk '{print $4}')      "$2"
 				fi
 				break 2
 				;;
@@ -89,8 +89,8 @@ permissions_menu() {
 					chown --reference="$2" "$1"
 					chmod --reference="$2" "$1"
 				else
-					chown $(stat -t "$2" | awk '{print $5":"$6}') $1
-					chmod $(stat -t "$2" | awk '{print $4}') $1
+					chown $(stat -t "$2" | awk '{print $5":"$6}') "$1"
+					chmod $(stat -t "$2" | awk '{print $4}')      "$1"
 				fi
 				break 2
 				;;
@@ -108,7 +108,7 @@ merge_menu() {
 
 	while true; do
 		info "Merged $1"
-		cat "$TMPFILE" | more
+		$PAGER "$TMPFILE"
 
 		if [ "$REJMERGE_MERGE_INFO" ]; then
 			info "$REJMERGE_MERGE_INFO"
@@ -150,7 +150,7 @@ diff_menu() {
 
 	while true; do
 		info "$1"
-		cat "$TMPFILE" | more
+		$PAGER "$TMPFILE"
 		while true; do
 			info_n "[K]eep [U]pgrade [M]erge [D]iff [S]kip? "
 			read -n1 CMD
@@ -203,34 +203,36 @@ file_menu() {
 }
 
 print_help() {
-	echo "usage: $REJMERGE_COMMAND [options]"
-	echo "options:"
-	echo "  -r,   --root <path>         specify alternative root"
-	echo "  -v,   --version             print version and exit "
-	echo "  -h,   --help                print help and exit"
+	cat <<EOF
+usage: $REJMERGE_COMMAND [options]
+options:
+  -r, --root <path>   specify alternative root
+  -v, --version       print version and exit
+  -h, --help          print help and exit
+EOF
 }
 
 parse_options() {
 	while [ "$1" ]; do
 		case $1 in
-			-r|--root)
-				if [ ! "$2" ]; then
-					echo "$REJMERGE_COMMAND: option $1 requires an argument"
-					exit 1
-				fi
-				REJMERGE_ROOT="$2"
-				REJMERGE_CONF="$2$REJMERGE_CONF"
-				REJECTED_DIR="$2$REJECTED_DIR"
-				shift ;;
-			-v|--version)
-				echo "$REJMERGE_COMMAND (pkgutils) $REJMERGE_VERSION"
-				exit 0 ;;
-			-h|--help)
-				print_help
-				exit 0 ;;
-			*)
-				echo "$REJMERGE_COMMAND: invalid option $1"
-				exit 1 ;;
+		-r|--root)
+			if [ ! "$2" ]; then
+				echo "$REJMERGE_COMMAND: option $1 requires an argument"
+				exit 1
+			fi
+			REJMERGE_ROOT="$2"
+			REJMERGE_CONF="$2$REJMERGE_CONF"
+			REJECTED_DIR="$2$REJECTED_DIR"
+			shift ;;
+		-v|--version)
+			echo "$REJMERGE_COMMAND (pkgutils) $REJMERGE_VERSION"
+			exit 0 ;;
+		-h|--help)
+			print_help
+			exit 0 ;;
+		*)
+			echo "$REJMERGE_COMMAND: invalid option $1"
+			exit 1 ;;
 		esac
 		shift
 	done
@@ -242,8 +244,8 @@ parse_options() {
 }
 
 files_regular() {
-	test -f $1 || return 1
-	test -f $2 || return 1
+	test -f "$1" || return 1
+	test -f "$2" || return 1
 	return 0
 }
 
@@ -259,7 +261,7 @@ main() {
 	if [ -f "$REJMERGE_CONF" ]; then
 		. "$REJMERGE_CONF"
 	fi
-	
+
 	REJECTED_FILES_FOUND="no"
 
 	# Check files
@@ -305,7 +307,7 @@ main() {
 	done
 
 	# Remove empty directories
-	for DIR in $(find $REJECTED_DIR -depth -type d); do
+	find "$REJECTED_DIR" -depth -type d | while read -r DIR; do
 		if [ "$DIR" != "$REJECTED_DIR" ]; then
 			rmdir "$DIR" &> /dev/null
 		fi
@@ -328,7 +330,8 @@ readonly REJMERGE_COMMAND="${0##*/}"
 REJMERGE_ROOT=""
 REJMERGE_CONF="/etc/rejmerge.conf"
 REJECTED_DIR="/var/lib/pkg/rejected"
-EDITOR=${EDITOR:-vi}
+EDITOR=${EDITOR:-/bin/vi}
+PAGER=${PAGER:-/bin/more}
 TMPFILE=$(mktemp) || exit 1
 
 main "$@"
